### ISSUE TITLE
登录获取 cred 错误

### ISSUE THREAD

**Issue by Morris-Lucifer** [enpitsuLin/skland-daily-attendance#20]
```> skland-daily-attendance@1.0.0 attendance /home/runner/work/skland-daily-attendance/skland-daily-attendance
> tsx main.ts

/home/runner/work/skland-daily-attendance/skland-daily-attendance/src/api/hypergryph.ts:21
    throw new Error(`登录获取 cred 错误:${data.msg}`)
          ^


Error: 登录获取 cred 错误:Key: 'GrantV2Req.token' Error:Field validation for 'token' failed on the 'required' tag
Key: 'GrantV2Req.appCode' Error:Field validation for 'appCode' failed on the 'required' tag
Key: 'GrantV2Req.type' Error:Field validation for 'type' failed on the 'required' tag
    at auth (/home/runner/work/skland-daily-attendance/skland-daily-attendance/src/api/hypergryph.ts:21:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at doAttendanceForAccount (/home/runner/work/skland-daily-attendance/skland-daily-attendance/src/index.ts:[14](https://github.com/Morris-Lucifer/skland-daily-attendance/actions/runs/7282501120/job/19844961632#step:8:15):20)
    at async Promise.all (index 0)
    at <anonymous> (/home/runner/work/skland-daily-attendance/skland-daily-attendance/main.ts:12:1)

Node.js v[18](https://github.com/Morris-Lucifer/skland-daily-attendance/actions/runs/7282501120/job/19844961632#step:8:19).18.2
 ELIFECYCLE  Command failed with exit code 1.
```
这是什么原因呢？

**Comment by moeyua** [comment]
登录信息过期了，重新获取一下 SKLAND_TOKEN 试试。

**Comment by Morris-Lucifer** [comment]
> 登录信息过期了，重新获取一下 SKLAND_TOKEN 试试。

好了，谢谢大佬
