### ISSUE TITLE
签到报错 Error: 登录获取 cred 错误:Key: 'GrantV2Req.token' Error:Field validation for 'token' failed on the 'required' tag

### ISSUE THREAD

**Issue by Montaro2017** [enpitsuLin/skland-daily-attendance#23]
```
/home/runner/work/skland-daily-attendance/skland-daily-attendance/src/api/hypergryph.ts:21
    throw new Error(`登录获取 cred 错误:${data.msg}`)
          ^


Error: 登录获取 cred 错误:Key: 'GrantV2Req.token' Error:Field validation for 'token' failed on the 'required' tag
Key: 'GrantV2Req.appCode' Error:Field validation for 'appCode' failed on the 'required' tag
Key: 'GrantV2Req.type' Error:Field validation for 'type' failed on the 'required' tag
    at auth (/home/runner/work/skland-daily-attendance/skland-daily-attendance/src/api/hypergryph.ts:21:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at doAttendanceForAccount (/home/runner/work/skland-daily-attendance/skland-daily-attendance/src/index.ts:14:[20](https://github.com/Montaro2017/skland-daily-attendance/actions/runs/7433660332/job/20232471308#step:8:21))
    at async Promise.all (index 0)
    at <anonymous> (/home/runner/work/skland-daily-attendance/skland-daily-attendance/main.ts:12:1)
```

**Comment by enpitsuLin** [comment]
如果最近遇到了 re-run 就好了

**Comment by Montaro2017** [comment]
> 如果最近遇到了 re-run 就好了

我昨天re-run了3次都失败了，今天好像没问题了

**Comment by Montaro2017** [comment]
不知道是啥问题啊，签到成功两天，失败一天，签到成功两天，失败一天
已经同步了最新的代码

**Comment by enpitsuLin** [comment]
🙈好像没办法 每个人的情况都不太相同

**Comment by Montaro2017** [comment]
好像这段时间又没问题了
