### ISSUE TITLE
偶尔签到失败，可能 ip 被风控

### ISSUE THREAD

**Issue by foreverlong** [enpitsuLin/skland-daily-attendance#39]
开发者您好，首先感谢您的工作。
想请问一下，action手动触发是可以的，但好像自动action会出现以下报错。（p.s. 如果重复签到也会报错，然后github会发邮件，是这样吗？）谢谢。
Run pnpm attendance
  pnpm attendance
  shell: /usr/bin/bash -e {0}
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    STORE_PATH: /home/runner/setup-pnpm/node_modules/.bin/store/v3
    SKLAND_TOKEN: ***
    SERVERCHAN_SENDKEY: ***
    BARK_URL: 
    SELECT_CHANNEL: 

> skland-daily-attendance@1.0.0 attendance /home/runner/work/skland-daily-attendance/skland-daily-attendance
> tsx main.ts

undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:45[2](https://github.com/foreverlong/skland-daily-attendance/actions/runs/10169142431/job/28125364769#step:8:2)7:27)
    at fullyReadBody (node:internal/deps/undici/undici:1[3](https://github.com/foreverlong/skland-daily-attendance/actions/runs/10169142431/job/28125364769#step:8:3)07:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:[4](https://github.com/foreverlong/skland-daily-attendance/actions/runs/10169142431/job/28125364769#step:8:4)536:7)
    at getBinding (/home/runner/work/skland-daily-attendance/skland-daily-attendance/src/api/skland.ts:38:1[6](https://github.com/foreverlong/skland-daily-attendance/actions/runs/10169142431/job/28125364769#step:8:6))
    at doAttendanceForAccount (/home/runner/work/skland-daily-attendance/skland-daily-attendance/src/index.ts:16:20)
    at async Promise.all (index 0)
    at <anonymous> (/home/runner/work/skland-daily-attendance/skland-daily-attendance/main.ts:12:1)

Node.js v1[8](https://github.com/foreverlong/skland-daily-attendance/actions/runs/10169142431/job/28125364769#step:8:8).18.2
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.

**Comment by enpitsuLin** [comment]
这个错误大概率是因为网络问题导致的，或者YJ的接口突然出现问题了，重新手动触发一下就好了，可能后面加一下错误重试的功能

**Comment by SamuNatsu** [comment]
> 这个错误大概率是因为网络问题导致的，或者YJ的接口突然出现问题了，重新手动触发一下就好了，可能后面加一下错误重试的功能

鹰角 API 被阿里云风控了，504 错误，返回网页 “很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。”

估计是对机房和一些不干净的非家庭 IP 下手了

错误同 <https://github.com/SamuNatsu/skland-daily-attendance-shell/issues/2>

**Comment by Hakuin123** [comment]
最近两天遇到了同样的问题…( ‘-ωก̀ )

**Comment by enpitsuLin** [comment]
Sad 不知道加个重试会不会好点🤡如果是被跑 CI 的机子风控的话重试估计解决不了问题，可能需要别的技术手段套一下

**Comment by enpitsuLin** [comment]
这个周末如果有时间我可能会试一下用 Cloudflare Wrap 代理请求避免 ip 被风控，如果最近还有人遇到这个问题的话暂时只能手动重新签到了

**Comment by Rayon642** [comment]
最新的代码运行action会出现405，不管怎么换代理重获token都报一样的错，有点头疼
`> skland-daily-attendance@1.0.0 attendance /home/runner/work/skland-daily-attendance/skland-daily-attendance
\> tsx main.ts

node:internal/process/task_queues:95
    runMicrotasks();
    ^

FetchError: [GET] "https://zonai.skland.com/api/v1/game/player/binding": 405 Not Allowed
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $fetch2 (file:///home/runner/work/skland-daily-attendance/skland-daily-attendance/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:[15](https://github.com/Rayon642/skland-daily-attendance/actions/runs/10353469478/job/28656452596#step:10:16))
    at getBinding (/home/runner/work/skland-daily-attendance/skland-daily-attendance/src/api/skland.ts:44:[16](https://github.com/Rayon642/skland-daily-attendance/actions/runs/10353469478/job/28656452596#step:10:17))
    at doAttendanceForAccount (/home/runner/work/skland-daily-attendance/skland-daily-attendance/src/index.ts:[18](https://github.com/Rayon642/skland-daily-attendance/actions/runs/10353469478/job/28656452596#step:10:19):20)
    at async Promise.all (index 0)
    at <anonymous> (/home/runner/work/skland-daily-attendance/skland-daily-attendance/main.ts:12:1)

Node.js v18.18.2
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by enpitsuLin** [comment]
> 最新的代码运行action会出现405，不管怎么换代理重获token都报一样的错，有点头疼 `> skland-daily-attendance@1.0.0 attendance /home/runner/work/skland-daily-attendance/skland-daily-attendance > tsx main.ts
> 
> node:internal/process/task_queues:95 runMicrotasks(); ^
> 
> FetchError: [GET] "[zonai.skland.com/api/v1/game/player/binding](https://zonai.skland.com/api/v1/game/player/binding)": 405 Not Allowed at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async $fetch2 (file:///home/runner/work/skland-daily-attendance/skland-daily-attendance/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:[15](https://github.com/Rayon642/skland-daily-attendance/actions/runs/10353469478/job/28656452596#step:10:16)) at getBinding (/home/runner/work/skland-daily-attendance/skland-daily-attendance/src/api/skland.ts:44:[16](https://github.com/Rayon642/skland-daily-attendance/actions/runs/10353469478/job/28656452596#step:10:17)) at doAttendanceForAccount (/home/runner/work/skland-daily-attendance/skland-daily-attendance/src/index.ts:[18](https://github.com/Rayon642/skland-daily-attendance/actions/runs/10353469478/job/28656452596#step:10:19):20) at async Promise.all (index 0) at (/home/runner/work/skland-daily-attendance/skland-daily-attendance/main.ts:12:1)
> 
> Node.js v18.18.2  ELIFECYCLE  Command failed with exit code 1.`

😩现在应该还是偶尔会被风控，特别是手动运行的时候，warp 代理应该是在 ci 中生效了的，我觉得还是要观察几天

**Comment by enpitsuLin** [comment]
应该是要宣布寄了，昨天还是概率被风控，今天已经全部需要阿里反爬的参数了，后面就需要逆向大佬的工作了

**Comment by TyrantG** [comment]
全完了🥲

**Comment by Rayon642** [comment]
森空岛的app甚至还搞了签到通知，估计是真不想让你玩自动签到了

**Comment by enpitsuLin** [comment]
从米游社开始有一个算一个，把日常奖励放在另一个应用里的都是傻逼东西🤡是真不想用你们这些傻逼社区，我™是来玩游戏的不是玩社区的

> 森空岛的app甚至还搞了签到通知，估计是真不想让你玩自动签到了

放心等过段时间应该还是会有解决方法的，但是不太好开源搞了，除非真有逆向大佬搞出来参数的。

**Comment by enpitsuLin** [comment]
好像今天把方舟签到需要的接口的风控解除了，只有登岛检票的接口会有问题

**Comment by SilentC1ty** [comment]
是不是理论上搞个docker容器然后里面搞个定时任务定时执行tsx main.ts就不会被风控了

**Comment by SamuNatsu** [comment]
> 是不是理论上搞个docker容器然后里面搞个定时任务定时执行tsx main.ts就不会被风控了

阿里云风控的逻辑不可知，加上个 docker 也不一定有用

[SamuNatsu/skland-daily-attendance-shell](https://github.com/SamuNatsu/skland-daily-attendance-shell) 提供的 docker 容器也被风控了

登岛检票会被风控，方舟签到则正常了
