### ISSUE TITLE
多账号报错

### ISSUE THREAD

**Issue by spriteQi** [enpitsuLin/skland-daily-attendance#58]
试了单个账号可以但是多个就会报错，是按照a,b,c的格式填写key的。

##[debug]Evaluating: secrets.SKLAND_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'SKLAND_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: secrets.SERVERCHAN_SENDKEY
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'SERVERCHAN_SENDKEY'
##[debug]=> null
##[debug]Result: null
##[debug]Evaluating: secrets.BARK_URL
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'BARK_URL'
##[debug]=> null
##[debug]Result: null
##[debug]Evaluating: secrets.SELECT_CHANNEL
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'SELECT_CHANNEL'
##[debug]=> null
##[debug]Result: null
##[debug]Evaluating condition for step: 'Run daily attendance'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run daily attendance
##[debug]Loading inputs
##[debug]Loading env
Run pnpm attendance
##[debug]/usr/bin/bash -e /home/runner/work/_temp/c9d707c0-5935-4145-b68[2](https://github.com/spriteQi/skland-daily-attendance-1/actions/runs/12130967447/job/33822761835#step:8:2)-897b9d11a6c6.sh

> skland-daily-attendance@1.0.0 attendance /home/runner/work/skland-daily-attendance-1/skland-daily-attendance-1
> tsx main.ts

wasm://wasm/001c6ec6:1

RuntimeError: memory access out of bounds
    at wasm://wasm/001c6ec6:wasm-function[41[3](https://github.com/spriteQi/skland-daily-attendance-1/actions/runs/12130967447/job/33822761835#step:8:3)]:0x66028
    at RsaPublic.getKeySize (/home/runner/work/skland-daily-attendance-1/skland-daily-attendance-1/node_modules/.pnpm/@originjs+crypto-js-wasm@1.1.1/node_modules/@originjs/crypto-js-wasm/lib/index.js:62[4](https://github.com/spriteQi/skland-daily-attendance-1/actions/runs/12130967447/job/33822761835#step:8:4)7:24)
    at RSAAlgo.getKeySize (/home/runner/work/skland-daily-attendance-1/skland-daily-attendance-1/node_modules/.pnpm/@originjs+crypto-js-wasm@1.1.1/node_modules/@originjs/crypto-js-wasm/lib/index.js:6920:29)
    at RSAAlgo.errorIfExceedSizeLimit (/home/runner/work/skland-daily-attendance-1/skland-daily-attendance-1/node_modules/.pnpm/@originjs+crypto-js-wasm@1.1.1/node_modules/@originjs/crypto-js-wasm/lib/index.js:6970:28)
    at RSAAlgo.encrypt (/home/runner/work/skland-daily-attendance-1/skland-daily-attendance-1/node_modules/.pnpm/@originjs+crypto-js-wasm@1.1.1/node_modules/@originjs/crypto-js-wasm/lib/index.js:6776:12)
    at Object.encrypt (/home/runner/work/skland-daily-attendance-1/skland-daily-attendance-1/node_modules/.pnpm/@originjs+crypto-js-wasm@1.1.1/node_modules/@originjs/crypto-js-wasm/lib/index.js:7077:23)
    at encryptRSA (/home/runner/work/skland-daily-attendance-1/skland-daily-attendance-1/src/crypto.ts:104:3[5](https://github.com/spriteQi/skland-daily-attendance-1/actions/runs/12130967447/job/33822761835#step:8:5))
    at getDid (/home/runner/work/skland-daily-attendance-1/skland-daily-attendance-1/src/utils.ts:143:14)
    at signIn (/home/runner/work/skland-daily-attendance-1/skland-daily-attendance-1/src/api/skland.ts:27:1[6](https://github.com/spriteQi/skland-daily-attendance-1/actions/runs/12130967447/job/33822761835#step:8:6))
    at doAttendanceForAccount (/home/runner/work/skland-daily-attendance-1/skland-daily-attendance-1/src/index.ts:16:3[8](https://github.com/spriteQi/skland-daily-attendance-1/actions/runs/12130967447/job/33822761835#step:8:8))

Node.js v18.18.2
 ELIFECYCLE  Command failed with exit code 1.
Error: 进程已结束，退出代码为 1.
##[debug]Finishing: Run daily attendance

**Comment by winerchan** [comment]
同样出现了该问题，目前正通过临时更改运行版本到41d9dd28ff512067bc2cb2bf76b589f719aa0698提交以规避

**Comment by enpitsuLin** [comment]
看起来可能是用的 wasm 在跑多个账户会有点问题，上面的 workaround 应该可以解决，后面把这个 wasm 的去掉好了

**Comment by enpitsuLin** [comment]
3fccb13edd1a887035ffcc62ab1890a0981d418f 之后逻辑上应该不会出现这个问题了

**Comment by spriteQi** [comment]
> [3fccb13](https://github.com/enpitsuLin/skland-daily-attendance/commit/3fccb13edd1a887035ffcc62ab1890a0981d418f) 之后逻辑上应该不会出现这个问题了

不行，直接用不了了，你看你自己的actions都报错了。

**Comment by enpitsuLin** [comment]
🙈太忙了没注意到 要手动引一下包

**Comment by spriteQi** [comment]
可以了，感谢！
